amount = float(input("Total bill amount? "))
service = input("Level of service? ")
num_of_ppl = int(input("Split how many ways? "))
if service.lower() == "good":
    tip = float(amount * 0.20)
    total = float(tip + amount)
    perperson = float(total/num_of_ppl)
    print ("Tip amount: ${:.2f}".format(tip))
    print ("Total amount: ${:.2f}".format(total))
    print ("Amount per person: ${:.2f}".format(perperson))
elif service.lower() == "fair":
    tip = float(amount * 0.15)
    total = float(tip + amount)
    perperson = float(total/num_of_ppl)
    print ("Tip amount: ${:.2f}".format(tip))
    print ("Total amount: ${:.2f}".format(total))
    print ("Amount per person: ${:.2f}".format(perperson))
elif service.lower() == "bad":
    tip = float(amount * 0.10)
    total = float(tip + amount)
    perperson = float(total/num_of_ppl)
    print ("Tip amount: ${:.2f}".format(tip))
    print ("Total amount: ${:.2f}".format(total))
    print ("Amount per person: ${:.2f}".format(perperson))
